string requester_id
string dataset_id
float64 rate
builtin_interfaces/Duration start_offset
builtin_interfaces/Duration end_offset
bool publish_clock
bool loop
---
Status status
uint64 messages_replayed
builtin_interfaces/Duration replayed_duration
---
float32 progress
builtin_interfaces/Duration current_offset
uint64 messages_replayed
Status status
