<?xml version="1.0"?>
<package format="3">
  <name>hc_robot_x1</name>
  <version>0.1.0</version>
  <description>Robot description, URDF, meshes and configuration profiles for X1 robot.</description>
  <maintainer email="czy33114@gmail.com">HC Teleop Team</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
